#%RAML 1.0
title: Download file API
baseUri: http://localhost:4025
mediaType: application/json

/download:
	/{fileId}:
	    get:
	        description: Downloads the file if it's shared
	        uriParameters:
	        	email:
	        		description: Email that requests the file
	        		type: string
